version: '3.7'

services:
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:80" # Le port 1080 du conteneur est mappé sur le port 80 de l'hôte
      - "1025:25" # Le port 1025 du conteneur est mappé sur le port 25 de l'hôte
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local
